
export const HeroList = () => {
  const heroes = [{name:"TAZIA",index:0,tribe:0,role:0,rarity:1,sname:"VIKING",des:"A skilled warrior in the Byzan. As a child, he was rescued by the Jarad, which is the powerful people of the tribe. After that, Tazia was trained to become a warrior of the tribe. With gratitude for his childhood heroes, he set up his training day after day until he became one of the strongest warriors in the tribe"},
  {name:"BULLOCK",index:1,tribe:1,role:1,rarity:2,sname:"MOON FALL",des:"A former Nakamatos council member. He formed his own rebel group as part of a plan to steal the power of De-Zentrum, because he was not chosen to be tested for powers. Therefore, he persuades people who wanted to gain power like him to rebelled the council. During the rush hour, he stole the power. Later on,he formed a new group call Ethern and soon thisnew group has become a new kingdom."},
  {name:"KWONDO",index:2,tribe:2,role:2,rarity:4,sname:"WAR MACHINE",des:"KwonDo was separated from his younger siblings since when he was a child and was sent by his parents toa military school at the age of 10. He stayed inthe military school for 5 years and received the first place to get into the military training. Twelve years later, he becomes the leader of the unit. He is an expert in using long-range weapons in the battlefield. While he is going to help people form bank robberies, he meets his brother who is the one robbing, so he wants to help his brother. He took his brother into the unit and tell his supervisor that his brother has talent and he did not want the army to lose this talent source, so the commander accepted his brother and put him in charge of Zet."},
  {name:"ORCA",index:3,tribe:3,role:3,rarity:3,sname:"SOUL TAKER",des:"An assassin of the Solis which was trusted by the leader of the tribe. One day, Orca was on a mission to explore the outer space, when he returns, a group of people invaded the Solis, causing almost everyone in the tribe to die. Orca’s wife and children died in this tragedy. He set out to take revenge on the group that destroyed his tribe."},
  {name:"AYLA",index:4,tribe:4,role:1,rarity:1,sname:"ZODIAC",des:"The daughter of Adelard, the King of Nakamatos, and is trained in battle by the kingdom’s knight in order to pass the test of obtaining power from the piece of De-Zentrum. Ten years later, she was put to the test for De-Zentrum’s powers. After gaining the power, she has become – which is a group that received power to protect their people."},
  {name:"MORA",index:5,tribe:0,role:4,rarity:0,sname:"",des:"An weapons mechanic in the Byzan. She always secretly sells the weapons she created to other cities. Because she is fascinated with technology, she wants to come out to exchange technology in Everfield rather than sit and make weapons in her own tribe alone. She wants to bring out her knowledge and abilities to let others know. She also likes to combine different types of weapons to create her own weapons."},
  {name:"DOTLER",index:6,tribe:1,role:0,rarity:3,sname:"RAIJIN",des:"A member of Ethen, he is a controversial person.He is often violent in various matters. He is also the leader of the Bruiser, which is the most violent group in Ethern. He had been slaughtering people who had affairs with him every day. He organizes a battle which bring people within the group to fight against each other in the arena."},
  {name:"YANO",index:7,tribe:2,role:3,rarity:1,sname:"ROBOT NINJA",des:"Yano was captured by a group of thieves when he was a child, but managed to escape. He later joins a gang of thugs to survive. Fifteen years later, he went to rob a bank and met his long-lost older brother, KwonDo. During the heist, KwonDo saw his skill in using close-range weapon and realized that Zet was his brother and wanted to help him to live a better life. Kwondo brought Zet into the army and introduced Zet to soldiers who were skilled in using sword to train his brother. Later, he came to work with KwonDo."},
  {name:"AXOIT",index:8,tribe:3,role:5,rarity:0,sname:"",des:"It is a species that belong to the Solis which is playful and it was a species that has supported the tribe for a long time. It is one species that is now a minority who can still use the power of gems in their fight for the survival of the Ethern’s invasion. Now, they are seeking for a place to settle in the ocean while protecting their gems which is their energy source."},
  {name:"MAPIUS",index:9,tribe:4,role:2,rarity:2,sname:"SOUL STEALER",des:"She was one of the people who passed the test of the Nakamatos. After she join Electus, she loses one of her arms from her battle with Abris, a monster that had invaded Nakamatos. Her right arm has become a prosthetic arm that can be used in battle with the power of the De-Zentrum. She is also a close friend of Ayla, King Adelard’s daughter. They always have a mini battle with each other to prove who’s better no matter what that battle is."},

] 
    
    return {heroes}
}